spring:
  web:
    resources:
      static-locations: classpath:static/
  thymeleaf:
    cache: false
  redis:
    database: 6
    password: 123456
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: zbbsmz_v75
    password: smzSMZ123
#    url: jdbc:oracle:thin:@192.168.100.70:1521:smz
#    username: zzbsmz_2022
#    password: smzSMZ123
#    url: jdbc:oracle:thin:@localhost:1521:smz
#    username: zbbsmzv50
#    password: smzSMZ123
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 'x'  FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    logSlowSql: true




server:
  port: 8081


mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.gxzh.survey.entity
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.gxzh.jxvueserver.mapper: debug