spring:
  redis:
    database: 2
    password: 123456
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:oracle:thin:@localhost:1521:orcl
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: zbbsmz_v75
      password: smzSMZ123
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 'x'  FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
server:
  port: 8081


mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.gxzh.survey.entity
  configuration:
    map-underscore-to-camel-case: true